# Generated by Django 4.0.6 on 2022-07-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_author_category_comment_post_postcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='rating',
            new_name='author_rating',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='post_category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='types_of_post',
        ),
        migrations.AddField(
            model_name='post',
            name='type_of_post',
            field=models.CharField(choices=[('NW', 'Новость'), ('AT', 'Статья')], default='NW', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=128),
        ),
    ]
